[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyobiee"
version = "0.1.7"
authors = [
  { name="Timur Kazyev", email="frmail@vk.com" },
]
description = "Python wrapper for OBIEE"
readme = "README.md"
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/kazei92/pyobiee"